version: '3'

networks:
  explorer_network:
    external:
      name: thesis_thesis_network

services:
  redis: 
    image: 'redis'
    container_name: 'rest-redis'
    restart: always
    command: ['--maxmemory-policy','noeviction','--requirepass','fabric-redis-pwd']
    ports:
      - 6379:6379
    networks:
      - explorer_network

  mysql:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    container_name: rest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thesis
      MYSQL_USER: rest_sa
      MYSQL_PASSWORD: rest_sa_pwd
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - explorer_network

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-api
    restart: always
    environment:
      TEST: "true"
    ports:
      - "3000:3000"
    # network_mode: host
    volumes:
      - ./../hyperledger-network/crypto-config:/blockchain/crypto-config
      - ./wallet:/rest-api/wallet
    networks:
      - explorer_network