OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: UiS
    Domain: uis.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: UiO
    Domain: uio.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: UiB
    Domain: uib.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1