apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-manager
  namespace: jhub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      volume-manager: "true"
rules: [] # The control plane automatically fills in the rules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistent-volume-admin
  labels:
    volume-manager: "true"
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistent-volume-claim-admin
  labels:
    volume-manager: "true"
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager
  labels:
    volume-manager: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-manager-rb
subjects:
- kind: ServiceAccount
  name: volume-manager # Name is case sensitive
  namespace: jhub
roleRef:
  kind: ClusterRole
  name: volume-admin
  apiGroup: rbac.authorization.k8s.io