apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uib-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi