apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jupyter-username-
spec:
  entrypoint: dag
  templates:
  - container:
      command:
      - pwd
      env:
      - name: NB_USER
        value: jovyan
      - name: PATH
        value: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - name: HOME
        value: /home/jovyan
      - name: JPY_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_ACTIVITY_URL
        value: http://hub:8081/hub/api/users/username/activity
      - name: JUPYTERHUB_ADMIN_ACCESS
        value: '1'
      - name: JUPYTERHUB_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_API_URL
        value: http://hub:8081/hub/api
      - name: JUPYTERHUB_BASE_URL
        value: /
      - name: JUPYTERHUB_CLIENT_ID
        value: jupyterhub-user-username
      - name: JUPYTERHUB_HOST
        value: ''
      - name: JUPYTERHUB_OAUTH_CALLBACK_URL
        value: /user/username/oauth_callback
      - name: JUPYTERHUB_SERVER_NAME
        value: ''
      - name: JUPYTERHUB_SERVICE_PREFIX
        value: /user/username/
      - name: JUPYTERHUB_SINGLEUSER_APP
        value: jupyter_server.serverapp.ServerApp
      - name: JUPYTERHUB_USER
        value: username
      - name: JUPYTER_IMAGE
        value: aliakbarrehman/jupyterhub:v1.0
      - name: JUPYTER_IMAGE_SPEC
        value: aliakbarrehman/jupyterhub:v1.0
      - name: MEM_GUARANTEE
        value: '1073741824'
      image: aliakbarrehman/jupyterhub:v1.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: '1073741824'
      securityContext:
        runAsGroup: 100
        runAsUser: 1000
      volumeMounts:
      - mountPath: /home/jovyan
        name: volume-username
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vw792
        readOnly: true
      workingDir: /home/jovyan/jupyterflow/jupyterflow
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    name: job-1
    serviceAccountName: default
  - container:
      command:
      - ls
      - -la
      - /home/jovyan
      env:
      - name: NB_USER
        value: jovyan
      - name: PATH
        value: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - name: HOME
        value: /home/jovyan
      - name: JPY_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_ACTIVITY_URL
        value: http://hub:8081/hub/api/users/username/activity
      - name: JUPYTERHUB_ADMIN_ACCESS
        value: '1'
      - name: JUPYTERHUB_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_API_URL
        value: http://hub:8081/hub/api
      - name: JUPYTERHUB_BASE_URL
        value: /
      - name: JUPYTERHUB_CLIENT_ID
        value: jupyterhub-user-username
      - name: JUPYTERHUB_HOST
        value: ''
      - name: JUPYTERHUB_OAUTH_CALLBACK_URL
        value: /user/username/oauth_callback
      - name: JUPYTERHUB_SERVER_NAME
        value: ''
      - name: JUPYTERHUB_SERVICE_PREFIX
        value: /user/username/
      - name: JUPYTERHUB_SINGLEUSER_APP
        value: jupyter_server.serverapp.ServerApp
      - name: JUPYTERHUB_USER
        value: username
      - name: JUPYTER_IMAGE
        value: aliakbarrehman/jupyterhub:v1.0
      - name: JUPYTER_IMAGE_SPEC
        value: aliakbarrehman/jupyterhub:v1.0
      - name: MEM_GUARANTEE
        value: '1073741824'
      image: aliakbarrehman/jupyterhub:v1.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: '1073741824'
      securityContext:
        runAsGroup: 100
        runAsUser: 1000
      volumeMounts:
      - mountPath: /home/jovyan
        name: volume-username
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vw792
        readOnly: true
      workingDir: /home/jovyan/jupyterflow/jupyterflow
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    name: job-2
    serviceAccountName: default
  - container:
      command:
      - ls
      - -la
      - /home/jovyan/data
      env:
      - name: NB_USER
        value: jovyan
      - name: PATH
        value: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - name: HOME
        value: /home/jovyan
      - name: JPY_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_ACTIVITY_URL
        value: http://hub:8081/hub/api/users/username/activity
      - name: JUPYTERHUB_ADMIN_ACCESS
        value: '1'
      - name: JUPYTERHUB_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_API_URL
        value: http://hub:8081/hub/api
      - name: JUPYTERHUB_BASE_URL
        value: /
      - name: JUPYTERHUB_CLIENT_ID
        value: jupyterhub-user-username
      - name: JUPYTERHUB_HOST
        value: ''
      - name: JUPYTERHUB_OAUTH_CALLBACK_URL
        value: /user/username/oauth_callback
      - name: JUPYTERHUB_SERVER_NAME
        value: ''
      - name: JUPYTERHUB_SERVICE_PREFIX
        value: /user/username/
      - name: JUPYTERHUB_SINGLEUSER_APP
        value: jupyter_server.serverapp.ServerApp
      - name: JUPYTERHUB_USER
        value: username
      - name: JUPYTER_IMAGE
        value: aliakbarrehman/jupyterhub:v1.0
      - name: JUPYTER_IMAGE_SPEC
        value: aliakbarrehman/jupyterhub:v1.0
      - name: MEM_GUARANTEE
        value: '1073741824'
      image: aliakbarrehman/jupyterhub:v1.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: '1073741824'
      securityContext:
        runAsGroup: 100
        runAsUser: 1000
      volumeMounts:
      - mountPath: /home/jovyan
        name: volume-username
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vw792
        readOnly: true
      - mountPath: ~/data/uio
        name: uio
        readOnly: true
      - mountPath: ~/data/uib
        name: uib
        readOnly: true
      workingDir: /home/jovyan/jupyterflow/jupyterflow
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    name: job-3
    serviceAccountName: default
  - container:
      command:
      - ls
      env:
      - name: NB_USER
        value: jovyan
      - name: PATH
        value: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - name: HOME
        value: /home/jovyan
      - name: JPY_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_ACTIVITY_URL
        value: http://hub:8081/hub/api/users/username/activity
      - name: JUPYTERHUB_ADMIN_ACCESS
        value: '1'
      - name: JUPYTERHUB_API_TOKEN
        value: 0e4cbc3dfd0b449f989d00d91778efea
      - name: JUPYTERHUB_API_URL
        value: http://hub:8081/hub/api
      - name: JUPYTERHUB_BASE_URL
        value: /
      - name: JUPYTERHUB_CLIENT_ID
        value: jupyterhub-user-username
      - name: JUPYTERHUB_HOST
        value: ''
      - name: JUPYTERHUB_OAUTH_CALLBACK_URL
        value: /user/username/oauth_callback
      - name: JUPYTERHUB_SERVER_NAME
        value: ''
      - name: JUPYTERHUB_SERVICE_PREFIX
        value: /user/username/
      - name: JUPYTERHUB_SINGLEUSER_APP
        value: jupyter_server.serverapp.ServerApp
      - name: JUPYTERHUB_USER
        value: username
      - name: JUPYTER_IMAGE
        value: aliakbarrehman/jupyterhub:v1.0
      - name: JUPYTER_IMAGE_SPEC
        value: aliakbarrehman/jupyterhub:v1.0
      - name: MEM_GUARANTEE
        value: '1073741824'
      image: aliakbarrehman/jupyterhub:v1.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: '1073741824'
      securityContext:
        runAsGroup: 100
        runAsUser: 1000
      volumeMounts:
      - mountPath: /home/jovyan
        name: volume-username
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vw792
        readOnly: true
      workingDir: /home/jovyan/jupyterflow/jupyterflow
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    name: job-4
    serviceAccountName: default
  - dag:
      tasks:
      - dependencies: []
        name: job-1
        template: job-1
      - dependencies:
        - job-1
        name: job-2
        template: job-2
      - dependencies:
        - job-1
        name: job-3
        template: job-3
      - dependencies:
        - job-1
        name: job-4
        template: job-4
    name: dag
  volumes:
  - name: volume-username
    persistentVolumeClaim:
      claimName: claim-username
  - name: kube-api-access-vw792
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: uio-pv
    persistentVolumeClaim:
      claimName: uio-pvc
  - name: uib-pv
    persistentVolumeClaim:
      claimName: uib-pvc