apiVersion: v1
kind: PersistentVolume
metadata:
  name: uib-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /c/Users/Rehman/Downloads/Thesis/master-thesis-uis/jupyterhub/volumes/uib
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
